runtime: php81
env: standard
service: default

runtime_config:
  document_root: public/
  skip_lockdown_document_root: true

env_variables:
  db_uesr: "1"
  db_pwd: ${DATABASE_PASS}
  db_name: "1"
  db_socket: "1"