runtime: php81
env: standard
service: default

runtime_config:
  document_root: public/
  skip_lockdown_document_root: true

env_variables:
  db_uesr: '%DB_USER%'
  db_pwd: '%DB_PASS%'
  db_name: '%DB_NAME%'
  db_socket: '%DB_SOCKET%'